### ISSUE TITLE
Server configuration error

### ISSUE THREAD

**Issue by z3t0** [Nyx0uf/MPDRemote#11]
No matter what settings I enter on Server configuration I get an error complaining "Invalid parameters"

**Comment by Nyx0uf** [comment]
Need more information.

**Comment by Nyx0uf** [comment]
No more informations, closing.

**Comment by mshkrebtan** [comment]
@Nyx0uf Hi! I have the same issue.

I have just bought and installed MPDRemote on my iPhone running iOS 11.1.1.
I am running MPD 0.20.11 on my macOS Sierra 10.12.6.

The app discovers my `mpd` server via Zeroconf, but when I tap _Save_, i just get the error: "Invalid parameters".

What do I do?
