### ISSUE TITLE
Xcode 9 unable to compile

### ISSUE THREAD

**Issue by inquisition** [Nyx0uf/MPDRemote#13]
Hello,

Since the Xcode 9 release, the app is unable to compile. I have no knowledge for how to solve this but do you plan to fix this?

I bought you app to support the development but I use the one from Github so I can customize it and make it look more iOS default style (I'd be happy to share it if you want).

Thanks!!
Arnaud

![screen shot 2017-09-29 at 11 21 34](https://user-images.githubusercontent.com/692801/31009681-a5ac8906-a508-11e7-9d13-88a2827962c0.png)

**Comment by Nyx0uf** [comment]
Yeah I fixed that and converted to Swift 4, but not pushed it yet, will do this weekend.

**Comment by inquisition** [comment]
Great !! Thanks !
