### ISSUE TITLE
stuck with blue screen

### ISSUE THREAD

**Issue by bounceme** [Nyx0uf/MPDRemote#14]
the app was working till recently, now it wont open, just shows a blue screen then after a while crashes

**Comment by Nyx0uf** [comment]
Is your MPD server running ? Nothing changed, there was no update in a while ? iOS update perhaps ?

**Comment by bounceme** [comment]
probably ios update (latest one, iphone 5s)

**Comment by Nyx0uf** [comment]
Do you still have this problem with the latest update (1.13) ?
