### ISSUE TITLE
Enable/disable sound volume control

### ISSUE THREAD

**Issue by inquisition** [Nyx0uf/MPDRemote#18]
Because my MPD Server volume control is disabled (to improve sound quality), I don't need to have a volume control UI in the Player controller. That's why I would like to have the ability to disable Volume Control from the app Settings. And by disabling Volume Control, I would expect the control to completely disappear from the Player view.

**Comment by Nyx0uf** [comment]
In 1.13 the slider is disabled if software volume control is disabled.

**Comment by inquisition** [comment]
Yes I saw that, this is better! But I think it would look even better if the volume control is removed.
