### ISSUE TITLE
Update library

### ISSUE THREAD

**Issue by inquisition** [Nyx0uf/MPDRemote#19]
I would like ability to update MPD database in case I add new music to my server. This could be done from the MPD Server setup controller.
Doing this would remove the need to login to my MPD server (moOde) to update.

**Comment by Nyx0uf** [comment]
Done in https://github.com/Nyx0uf/MPDRemote/commit/9c14d0a85ade84e029dbcd2f2aa8b22517716c61

**Comment by inquisition** [comment]
Great !

**Comment by inquisition** [comment]
My feeling is that the current implemented feature will manually check for content update but do not ask the MPD server to update the MPD database. Do you confirm ?
