### ISSUE TITLE
Submit to App Store?

### ISSUE THREAD

**Issue by brendan-r** [Nyx0uf/MPDRemote#2]
Hello there,

This looks fantastic! 

Do you have any intention of putting it up on the app store?

**Comment by Nyx0uf** [comment]
I'm thinking about it. But I need to fix some annoying bugs first.

**Comment by odedia** [comment]
If money is the issue as the front page suggests, I'll be happy to post it under my personal developer account. Free of charge ofcourse, and the app will be free as well.

**Comment by Nyx0uf** [comment]
I'll try to put it on the app store in February

**Comment by rodrigoreyes79** [comment]
Waiting for this!!!

**Comment by dch** [comment]
I'm happy to pay for this too, MPoD appears to have been deleted by Apple so the time is right for a new entrant :-)

**Comment by Nyx0uf** [comment]
For info, the app has been submitted for review, but was rejected because :

 _Your app includes protected album cover artworks in app icons, screenshots or previews without the necessary authorization._

I'll change the screenshots and re-submit.

**Comment by Nyx0uf** [comment]
OK finally got it validated after making a video to prove them the app works…

https://itunes.apple.com/us/app/mpdremote/id1202933180?ls=1&mt=8

**Comment by dch** [comment]
Bought it! Enjoy -:)





On Wed, 1 Mar 2017, at 07:55, Nyx0uf wrote:

> OK finally got it validated after making a video to prove them the app
> works…

>

> https://itunes.apple.com/us/app/mpdremote/id1202933180?ls=1&mt=8

>

> --

> You are receiving this because you commented.

> Reply to this email directly or view it on GitHub:

> https://github.com/Nyx0uf/MPDRemote/issues/2#issuecomment-283260553





—

  Dave Cottlehuber

  +43 67 67 22 44 78

  Managing Director

  Skunkwerks, GmbH

  http://skunkwerks.at/

  ATU70126204

  Firmenbuch 410811i

**Comment by cpitclaudel** [comment]
Looks like the app was dropped; will you put it back up?
