### ISSUE TITLE
Display music format

### ISSUE THREAD

**Issue by inquisition** [Nyx0uf/MPDRemote#20]
From the Player view I would like to know what is the format of the currently playing music with the following information:
- file format (e.g. flac, aac, ogg etc...)
- bit rate (e.g. 128kbps)
- bit depth (e.g. 24bit)

**Comment by inquisition** [comment]
I'm not sure the MPD API provides this information.

**Comment by Nyx0uf** [comment]
I don't see the point ? What are the benefits ?

**Comment by inquisition** [comment]
I use my MPD server as high resolution audio server. It is quite important for me to know what I am listening to. This might not be important for the casual user.

**Comment by Nyx0uf** [comment]
> I use my MPD server as high resolution audio server

Same, I only have flac.

> It is quite important for me to know what I am listening to.

But you already know your files are high-res, why do you care if the file is say flac or alac, 16b or 24b ? bitrate for a lossless file is irrelevant.

**Comment by Jazz4u2** [comment]
Bit rate and bit depth are indeed relevant.  Agree with inquisition that this would be useful.

**Comment by inquisition** [comment]
Maybe it is me being weird but I like to know the information about my music. I don't care much about the format but bit rate and bit depth are important to me.

**Comment by Nyx0uf** [comment]
done in 111e7da4e2c79b05b2bdc92ca7cb841977736a52

The MPD API only provide samplerate, bit depth and number of channels, so there will be no bitrate displayed

**Comment by inquisition** [comment]
Awesome !
