### ISSUE TITLE
Playlists management

### ISSUE THREAD

**Issue by inquisition** [Nyx0uf/MPDRemote#21]
I would like ability to create new playlist(s) and then add tracks to playlist from the Album details view. Would be great if the playlist could be store on the MPD server but if not possible playlist could be create locally and synced across devices through iCloud.

**Comment by Nyx0uf** [comment]
Okay I improved playlist management with 9af3b16601ef18426b06e55b4ab7a46823b80ec7

If you want to try and give me feedback I can add you to TestFlight, just send me your app store account email to contact.mpdremote@gmail.com

**Comment by inquisition** [comment]
Sent you my TestFlight email account. Thanks.

**Comment by Jazz4u2** [comment]
Hi, please add me to TestFlight for playlist management updates, thanks.  
I would like to suggest a setting to control behavior of a new library selection added to "active playlist" via the now playing function:  1.  Play only newly selected file and next files in the same folder as selected file (this is the current behavior, which clears the previous selection and plays through the songs in the folder after the selected file) 2. Play only selected file (clear all other selections in active playlist, play the selected file, then stop) 3. Play selected file now (stop current selection and play new selection before playing remaining files in active playlist). 3.  Add selected file to active playlist after currently playing song, so it plays next. 4.  Add selection to end of active playlist.
I also suggest an On/Off setting to consume files in active playlist after playing, On=consume, Off=preserve.
The above suggestions provide the same active playlist functions as MPoD/MPaD.

**Comment by Nyx0uf** [comment]
You are still added in TestFlight.

Not sure I understood correctly what you want though

**Comment by Jazz4u2** [comment]
Thanks.
I tested the update and found that the editing of existing, saved playlists could be done. But I could not find a way to create a new saved playlist, or to create or edit an active playlist composed of more than one song or album.  The suggestions I made are essentially the same as MPoD in regard to the "now playing" functions.  It may be a lot to ask at this stage in development.  If you get to that point, feel free to ask any questions so I can clarify the specifics.

One thing that appears to be an issue is that there is no "now playing" function when in the playlists page.  

Thanks so much for your great work on MPDRemote.  It's working better all the time.
-Mark

On Dec 11, 2017, at 12:28 AM, Nyx0uf <notifications@github.com> wrote:

You are still added in TestFlight.

Not sure I understood correctly what you want though

**Comment by Nyx0uf** [comment]
I didn't use MPoD and I don't use playlists, so I don't know how MPoD worked ;)

**Comment by Jazz4u2** [comment]
Ok, understood.  But  I would like to suggest that the "now playing" window should appear from the playlists view, to provide the same controls (play/pause, volume, next song, shuffle, repeat ) as from the Albums, Artists, and Genres views.

**Comment by Jazz4u2** [comment]
One other issue - the album art in the large "now playing" view does not update when playing through a playlist from various albums.  It will update the album art after exiting the large view.

**Comment by Jazz4u2** [comment]
Build 10233 works great!  Both issues (now playing function for playlists, and album art update in now playing view) are resolved.  Thanks!

**Comment by Jazz4u2** [comment]
For future development I suggest expanding functions in the "active playlist", aka "now playing list".  A feature to select a song from an album without clearing the other selections in the "now playing" list, and also to view, add, delete, and reorder songs to the "now playing" list.

**Comment by Nyx0uf** [comment]
@Jazz4u2 Can you open a separate issue for this please ?

**Comment by Jazz4u2** [comment]
Yes, will do.
