### ISSUE TITLE
Widget to control music

### ISSUE THREAD

**Issue by inquisition** [Nyx0uf/MPDRemote#23]
I would like to have a widget to control music without the need to open the app (Previous, Play/Pause, Next, Title, Artist). 
If MPD Remote is running in background and if something is playing on my MPD Server (moOde), then I could control my music from the iOS control center or by Force Touch app icon.

**Comment by Nyx0uf** [comment]
done in 1f5d714496eb491bdcc17f762b446a13c20c4974

**Comment by inquisition** [comment]
Super !

**Comment by GeofP** [comment]
How do I use this widget?
