### ISSUE TITLE
pause/play button inversed

### ISSUE THREAD

**Issue by GeofP** [Nyx0uf/MPDRemote#24]
I have mpd running on a Rasperry Pi and have been using MPod sucessfully for some time. I now use an iPhone SE with IOS 11 and since MPoD is not compatible with this, purchased MPDRemote on 2nd Dec, ver 1.13 (9553).  I can control the play of music on the Pi but appear to be missing some of the features shown when advertising the app.

My screen references below relate to the iPhone Screenshots shown on https://itunes.apple.com/us/app/mpdremote/id1202933180?mt=8 , where screen 1 is the left screenshot.

1.  Screen 2 only lists the tracks on the album, not the options for Album, Artists, Genres and Playlists

2.  The album covers are all blank. If I look at "Clear cache (x.xxMB)" on server configuration screen, the x.xxMB figure very gradually increases but has never gone above about 1.3MB, then goes back to < 0.80MB when the app is closed then opened again.  I assume this is the cache for the album covers but no covers appear in the display.

3.  Comments on the screen showing the time line, back, pause/play forward and vol control (screen 3):

3.1.  The play symbol is shown when the music is playing and pause when it is paused.  I expected the opposite i.e. pressing the symbol performs the action, which is the case when shown bottom right corner of the screen that shows lists the tracks in the selected album (screen 2).

3.2.  If click on track to select it for playing when set to random (top right cross symbol made with 2 arrows, in black), it plays another track, not the one selected.

My configuration:

MPD runs on a Rasperry Pi with the music directory on an attached USB drive in directory /media/500G_drive/CD_copies_flac

I have 311 albums

Music files are in the flac format and contains tags for title, artist, album artist, album, track and some others.
The file structure is Artist/Album/track eg W:\500G_drive\CD_copies_flac\Alison Krauss\Windy City\01 Losing You
Each album directory has a album cover file called folder.jpg, typically 20 to 60KB

I use Lighttpd on a 2nd Raspberry Pi for the covers server.
There is a symbolic link in /var/www/ for covers -> /media/500G_drive/CD_copies_flac

**Comment by Nyx0uf** [comment]
> Screen 2 only lists the tracks on the album, not the options for Album, Artists, Genres and Playlists

Didn't understand

> The album covers are all blank. If I look at "Clear cache (x.xxMB)" on server configuration screen, the x.xxMB figure very gradually increases but has never gone above about 1.3MB, then goes back to < 0.80MB when the app is closed then opened again. I assume this is the cache for the album covers but no covers appear in the display.

Hopefully fixed in 1.14

> 3.1. The play symbol is shown when the music is playing and pause when it is paused. I expected the opposite i.e. pressing the symbol performs the action, which is the case when shown bottom right corner of the screen that shows lists the tracks in the selected album (screen 2).

Weird I'll take a look

> 3.2. If click on track to select it for playing when set to random (top right cross symbol made with 2 arrows, in black), it plays another track, not the one selected.

OK, i'll fix it in a future version

**Comment by GeofP** [comment]
Thank you for your quick reply.

Re: Didn't understand.  Perhaps my question should be "How do I get to the options for Album, Artists, Genres and Playlists?"

This is what is shown on the itunews.apple web page: 
![itunes apple web page screen 2](https://user-images.githubusercontent.com/6610094/33554396-75e6ff56-d8f4-11e7-9839-756a6fa95ff0.jpg)

This is my screen 2:
![my screen 2](https://user-images.githubusercontent.com/6610094/33554768-f4ebdeec-d8f5-11e7-94b9-456980d46fa0.jpg)

**Comment by GeofP** [comment]
OK, that works.  Thanks. 

Looking forward to 1.14 to see if that fixes the album covers problem.

Am I correct to think that I don't need any special code on the Pi serving the covers?  You give some on the Wiki configuration page, "So my nginx server configuration is very simple:"

**Comment by Nyx0uf** [comment]
Just enter the same parameters as you did for MPoD

**Comment by GeofP** [comment]
Now have 1.14 (10229) and that fixes the album covers, thank you
