### ISSUE TITLE
When mpd server is not available.

### ISSUE THREAD

**Issue by GeofP** [Nyx0uf/MPDRemote#26]
If the ip address for the mpd server is not valid because the iPhone is in a different location or the WiFi signal is turned off, starting MPDRemote results in a blue screen and the program hangs.

It would be useful for the program to run with the cached database so it could be searched e.g. to review ones music collection when away from the mpd server.

**Comment by Nyx0uf** [comment]
settings are cached, it hangs because server is unreachable and there is a 20 or 30sec timeout.

There won't ever be a local copy of the MPD database.

**Comment by inquisition** [comment]
+1 for this. Showing a cache of the library would probably help promote your app to friends when we are outside Home.
