### ISSUE TITLE
Image caching

### ISSUE THREAD

**Issue by odedia** [Nyx0uf/MPDRemote#4]
Great project!

I think there's a bug in the image caching. See screenshot:

https://www.amazon.com/photos/share/kMVUUKNRJUrmjsu9j9xtW2iDMQls0HnRCDCfubGWlo9

On the moode web interface the cover art appears correctly.

Two other nice-to-haves:
- swipe down on "now playing" to go back to song list, similar to stock Music app.
- The menu buttons are huuuuge
- Add a "Shuffle all" option.

Thanks!

**Comment by Nyx0uf** [comment]
Yeah I know I have a problem with image caching, I'll fix it when I can, I'm doing this on my free time and I have not much

1 - I have something in mind to show the songs list of an album.
2 - As I said I'm not a designer and I don't like spending time doing stuff like this
3 - Shuffle all music in the library ?

Thank you for the report!

**Comment by odedia** [comment]
If you can point me to the right location in the code I can have a look around. 
Also, my sister is a good designer if you want some help.

**Comment by odedia** [comment]
Oh and yes, I meant a one button "shuffle all songs in the library".

**Comment by Nyx0uf** [comment]
Okay for the shuffle button, I'll add it to my todo list.

As for the icons, they just need to be consistent across the app, especially the navigation bar icons (menu, shuffle, repeat, magnifying glass). The play / pause / next / previous icons look fine to me.

**Comment by Nyx0uf** [comment]
Can you retry with the last version from master ?

**Comment by odedia** [comment]
Sorry, still the same issue.

**Comment by odedia** [comment]
You can get the icons and design elements from here:

https://www.amazon.com/clouddrive/share/ZcD1UiYT6x5dq0CYGQhjc3t8EJWO3JtV3gtC7vRqBRb?ref_=cd_ph_share_link_copy

Thanks.

**Comment by Nyx0uf** [comment]
For you covers problem, what is your library hierarchy, what web server are you using ?

Thanks for the icons, but I'll need them as 3x size

**Comment by odedia** [comment]
Here it is:

https://www.amazon.com/clouddrive/share/NeCIlcDUrA859SAakUmFNzaB07pPfp69WKw7iQ0xHgO?ref_=cd_ph_share_link_copy

I'm using moode as web server. It's working fine when I use the web interface.
Library hierarchy is just a list of folders per album.

**Comment by Jazz4u2** [comment]
I'm having the image caching issue also.  I use MPod and MPad (up to iOS 10) to control my Bryston BDP-1 .  I am still using mPad on iOS 10. The MPDRemote app works great for playing my large library via NAS shared on a USB drive connected to the router.  I am using the MPD server version 0.18.21 running on the BDP-1.  MPDRemote will not display any cover art.  My cover art filenames are "Folder.jpg" and I've tried using that filename in the MPD Server settings.  Also tried adding files named "cover.jpg" with the standard filename setting, but no cover art appears.  The MPDRemote settings are exactly the same as on MPod and MPad, (except they do not specify Port 80 for http) and they display all cover art.

**Comment by Nyx0uf** [comment]
Could you try to send me the logs, from the settings view ?

Also if your covers are named Folder.jpg, don't set the name to cover.jpg

**Comment by Jazz4u2** [comment]
Ok, sent to contact.mpdremote@gmail.comontact <mailto:contact.mpdremote@gmail.comontact>  via the app.

Thanks!

-Mark

**Comment by Jazz4u2** [comment]
Ok, please see attached.

 

Also sent to contact.mpdremote@gmail.com <mailto:contact.mpdremote@gmail.com>  via the app.

 

MPDRemote 1.13 (9553)

iOS 11.1.2

 

MPD server:

192.168.1.15

6600

 

 

Cover server:

http://bryston-bdp-1.local/music

80

Folder.jpg

**Comment by Jazz4u2** [comment]
Database is served by Apache/2.2.22 (Debian) Server at bryston-bdp-1.local Port 80
Folder heierarchy is 4 levels deep:  <share address>/<artist name>/<album name>/<FLAC files and Folder.jpg>

**Comment by Jazz4u2** [comment]
Share address / artist name / album name / music files and Folder.jpg

**Comment by Nyx0uf** [comment]
@Jazz4u2 Can you send me your email for your App Store account to contact.mpdremote@gmail.com, I'll add you to TestFlight to try and debug it with you

**Comment by Nyx0uf** [comment]
Should be fixed in 1.14. Thanks to @Jazz4u2 for his help
