### ISSUE TITLE
Playlists loading

### ISSUE THREAD

**Issue by baloo** [Nyx0uf/MPDRemote#6]
In playlist view, the play action should use `load` method instead of duplicating the tracks in a new playlist.
The problem is that `listplaylistinfo` may not return the full url, this is especially true if the url is http with password protection. MPD will strip the login and password from the url. Replaying the tracks with stripped-login/password will fail.

`load` method does not have that problem.

**Comment by Nyx0uf** [comment]
Should be ok, thanks for reporting

**Comment by baloo** [comment]
<3 Thank you so much.
