### ISSUE TITLE
Play queue

### ISSUE THREAD

**Issue by gabhab** [Nyx0uf/MPDRemote#7]
I really love this app - very happy to have been able to buy something that works so well with my large mpd library, I'm amazed at how fast it is (especially in comparison to mpod).

The one thing I'm wondering is if there is, or could be, a way to see/navigate the play queue, other than just moving backwards and forwards and finding out what's there.

**Comment by Nyx0uf** [comment]
Currently there is nothing, but it is on my todo list

**Comment by gabhab** [comment]
Thank you very much - and thanks for writing the app, it's already great.

**Comment by Nyx0uf** [comment]
fixed in 1.11
