### ISSUE TITLE
Configure mpd server outputs

### ISSUE THREAD

**Issue by drehren** [Nyx0uf/MPDRemote#8]
Hi, good app.

 I would like to see a place to configure the server outputs. Mine has 3 and I sometimes I need to disable or enable one and can't do that from this app.

Thanks.

**Comment by Nyx0uf** [comment]
I'll se what I can do

**Comment by Nyx0uf** [comment]
I implemented it in https://github.com/Nyx0uf/MPDRemote/commit/dc7d1d3ec239ad1bcffaec61f27609f72b0886f2

This will be available in 1.10 version, which I just submitted for validation.

**Comment by drehren** [comment]
Thanks!

**Comment by Nyx0uf** [comment]
update is now available
