### ISSUE TITLE
3D touch crashing on iPhone 7

### ISSUE THREAD

**Issue by drehren** [Nyx0uf/MPDRemote#9]
When doing 3D touch on an Album or Playlist the app crashes.

**Comment by Nyx0uf** [comment]
Does it always happen ? I don't have a force-touch capable device and I can't reproduce it in the simulator

**Comment by drehren** [comment]
It's working now in Albums, but I've found that is failing in the others... it happens after I visit the Playlist page, if I don't the app doesn't crash in neither Artists or Genres.
It always crashes in the Playlist page.

**Comment by Nyx0uf** [comment]
For info : It's only implemented for Albums and Playlists

**Comment by Nyx0uf** [comment]
OK I found the problem

**Comment by Nyx0uf** [comment]
fixed in 1.11
